# Generated by Django 2.0.1 on 2019-06-27 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Url')),
                ('work_phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Work phone')),
                ('mobile_phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Mobile phone')),
                ('agency_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Agency name')),
                ('realtor_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Realtor name')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='City')),
                ('district', models.CharField(blank=True, max_length=150, null=True, verbose_name='District')),
                ('street', models.CharField(blank=True, max_length=150, null=True, verbose_name='Street')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Real estate detail',
                'verbose_name_plural': 'Real estate details',
            },
        ),
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='Word')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Search word',
                'verbose_name_plural': 'Search words',
            },
        ),
        migrations.AddField(
            model_name='realestatedetail',
            name='search_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_detail', to='real_estate.SearchWord'),
        ),
    ]
