# Generated by Django 2.0.1 on 2019-06-29 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_auto_20190628_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
                ('phone', models.CharField(max_length=30, verbose_name='Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Phone number',
                'verbose_name_plural': 'Phone numbers',
            },
        ),
        migrations.RemoveField(
            model_name='realestatedetail',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='realestatedetail',
            name='work_phone',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='real_estate.RealEstateDetail'),
        ),
    ]
